services:
  app: 
    container_name: polydocs-front
    image: node:20-alpine
    working_dir: /src/app
    ports:
      - 3100:3000
      # L'app est exposée sur le port 3100. Même si c'est marqué localhost:3000 dans le terminal, il faut aller sur localhost:3100.
    volumes:
      - .:/src/app
      - node_modules:/src/app/node_modules
    command: sh -c "npm install && npm run dev"

volumes:
  node_modules: